version: 2
updates:
  - package-ecosystem: gomod
    directories: ["/", "/example", "providers/**/"]
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
